development:
  adapter: postgresql
  encoding: utf8
  database: congoweek2014_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: congoweek2014_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: congoweek2014_production
  pool: 5
